#pragma kernel CSGeometry
#pragma kernel CSColor

#include "Assets/Shaders/Displacement/VertexDisplacement.hlsl"
#include "Assets/Shaders/Displacement/Normal.hlsl"
#include "Assets/Shaders/Rendering/PlanetColor.hlsl"

StructuredBuffer<float3> _BaseVertices;
RWStructuredBuffer<float3> _DisplacedVertices;
RWStructuredBuffer<float3> _Normals;
RWStructuredBuffer<float4> _VertexColors;

[numthreads(64, 1, 1)]
void CSGeometry(uint3 id : SV_DispatchThreadID)
{
    _DisplacedVertices[id.x] = ApplyVertexDisplacement(_BaseVertices[id.x]);

    Normal normalInfo = (Normal)0;
    normalInfo.Initialize(_BaseVertices[id.x]);
    float3 finalNormal = normalInfo.GetNormal();

    _Normals[id.x] = finalNormal;
}

[numthreads(64, 1, 1)]
void CSColor(uint3 id : SV_DispatchThreadID)
{
    float3 color;
    float intensity;
    CalculateColor_float(_DisplacedVertices[id.x], _Normals[id.x], color, intensity);

    _VertexColors[id.x] = float4(color, intensity);
}
