#pragma kernel CSMain

#include "Assets/Shaders/Displacement/VertexDisplacement.hlsl"
#include "Assets/Shaders/Displacement/Normal.hlsl"

StructuredBuffer<float3> _BaseVertices;
RWStructuredBuffer<float3> _DisplacedVertices;
RWStructuredBuffer<float3> _Normals;

RWTexture2D<float4> Result;

[numthreads(64, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    _DisplacedVertices[id.x] = ApplyVertexDisplacement(_BaseVertices[id.x]);

    Normal normalInfo = (Normal)0;
    normalInfo.Initialize(_BaseVertices[id.x]);
    float3 finalNormal = normalInfo.GetNormal();

    _Normals[id.x] = finalNormal;
}
